### ISSUE TITLE
Gmail contact returning empty contacts even on source=adress_book

### ISSUE THREAD

**Issue by tyhunt99** [nylas/nylas-python#104]
I am trying to test out the client and have an email with a single user in my address book. It is my work email so I have many emails in the account.

This returns several unknown and empty emails, including what I assume are ones generated from emails.
```python
client = nylas.APIClient(APP_ID, APP_SECRET, AUTH_TOKEN)
for contact in client.contacts:
    print(contact.as_json())
```

However even when adding `source=address_book` I get less, but still some empty emails.
```python
client = nylas.APIClient(APP_ID, APP_SECRET, AUTH_TOKEN)
for contact in client.contacts.where(source='address_book'):
    print(contact.as_json())
```

Am I misusing the source filter? I am currently using `nylas==4.2.0`

**Comment by tyhunt99** [comment]
Also not sure if this is related or not email_adresses always appears to be empty lists, even for known contacts

**Comment by tyhunt99** [comment]
I am getting the same result via curl. So maybe I am misunderstanding the source filter. Does `source=address_book` indicate only officially created contacts or will it also pull them from the emails?

**Comment by BenLloydPearson** [comment]
Thanks for reporting this @tyhunt99, release 4.8.0 should fix the issue you are facing. See #125 

It turns out that contact.email_addresses wasn't returning the proper information, in 4.8.0 we changed this to contact.emails, which now returns the list of email addresses you are looking for. 

As for the issue with your source filter, some providers will automatically add contacts to user's address books when certain criteria are met. For example, Gmail will add any email addresses you have sent an email to to address_book.
