### ISSUE TITLE
APIClient.account does not contain billing_state

### ISSUE THREAD

**Issue by mcrowson** [nylas/nylas-python#128]
When creating an APIClient with an access token, the account parameter does not contain the billing_state. 

If i use the client.accounts.all() and find the account in question, it does have the billing_state. It would be nice to have the client.account rather than search through all client.accounts.all() and find the billing_state of a user.

**Comment by BenLloydPearson** [comment]
Thanks for mentioning this @mcrowson! 

The `billing_state` attribute is only available via the [accounts management](https://docs.nylas.com/reference#aclient_idaccounts) endpoint because it needs to be possible to activate/deactivate accounts without knowledge of the access token. We don't have any plans right now to add this attribute to the [account endpoint](https://docs.nylas.com/reference#accounts)

The best way to handle this would probably be to get the `id` of the account in question and call APIClient.accounts.get('{id}'), with APIClient being a Nylas client that has been passed only the app id and app secret. An example would look like this:

```
from nylas import APIClient
nylas_account = APIClient(
    CLIENT_ID,
    CLIENT_SECRET,
    ACCESS_TOKEN
)
account = nylas_account.account

nylas_app = APIClient(
    CLIENT_ID,
    CLIENT_SECRET
)
managed_account = nylas_app.accounts.get(account.id)
print(managed_account.billing_state)
```

Notice the two versions of `APIClient`, `nylas_account` to manage the specific account and `nylas_app` to manage the app.
