### ISSUE TITLE
Bug: Draft Tracking Content Not Passed To Send() - Python

### ISSUE THREAD

**Issue by SungLee05** [nylas/nylas-python#165]
The tracking and version objects are not being added to the new draft data when IDs are not set. 

Seems like there was a similar issue with Nylas-NodeJS that had been resolved a month ago (**_link to the resolved issue here_** - https://githubmemory.com/repo/nylas/nylas-nodejs/issues/231)

Similar to the NodeJS issue above, I believe this is the line that needs to be updated for Python - https://github.com/nylas/nylas-python/blob/main/nylas/client/restful_models.py#L483

**Comment by mrashed-dev** [comment]
@SungLee05 Thanks for opening this issue! What version are you on? We just had a big release 5.0.0 release of the SDK and I believe the issue was fixed (#153) as I noticed the Python SDK did the same thing as the Node SDK did (same issue as you posted). Can you try updating to 5.0.0 and letting me know if it still is a problem? Thanks!

**Comment by SungLee05** [comment]
@mrashed-dev thanks for the prompt response! I appreciate it. Quick question, if updating the version to 5.0.0 isn't an option, is there a workaround for this issue?

**Comment by mrashed-dev** [comment]
@SungLee05 no problem! Are you able to make a local change to the library? The fix is only a couple of lines, here's the commit:

https://github.com/nylas/nylas-python/pull/153/commits/29f61d53053543eac23cd7292d635971ae942fa3

If you add these 2 lines then your issue should be fixed.

**Comment by mrashed-dev** [comment]
@SungLee05 I'm closing this ticket for now, let us know if you have any other issues.
